# Generated by Django 4.2.11 on 2024-03-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_recipe_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='opps',
            field=models.IntegerField(null=True),
        ),
    ]
