# Generated by Django 4.2.11 on 2024-03-14 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_recipe_opps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='opps',
        ),
    ]
