# Generated by Django 4.2.11 on 2024-03-15 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment',
        ),
    ]
