# Generated by Django 4.2.11 on 2024-03-17 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
